hrr/urls.py
from django.conf.urls import url, include, re_path
from ajax_select import urls as ajax_select_urls
from django.views.decorators.csrf import csrf_exempt
from django.views.generic import RedirectView

from hrr.views import IndexView
urlpatterns = [
	re_path(r'^$', IndexView.as_view(), name='index'),
	#re_path(r'^$', views.IndexView2, name='index'),
]

rowing/urls.py
from django.conf.urls import url, include, re_path
from ajax_select import urls as ajax_select_urls
from django.views.decorators.csrf import csrf_exempt
from django.views.generic import RedirectView

from . import views

from .views import IndexView, RowerList, RowerDetail, RaceList, RaceDetail, RankingView, AboutView, ClubList, ClubDetail, RowerSearch, CompetitionView, CompetitionResults, RowerCompare, Compare, IndexView2, KnockoutView, WeatherCalc, RowerCorrect, ResultCorrect, RowerMerge
urlpatterns = [
    #re_path(r'^$', views.current_datetime, name='index'),
    #re_path(r'^recalculate/$', views.CalculateView),
    #re_path(r'^$', views.IndexView.as_view(), name='index'),
    re_path(r'^$', views.IndexView2, name='index'),
    re_path(r'^about/$', views.AboutView.as_view(), name='about'),
    re_path(r'^rowers/$', RowerList.as_view(), name="rower-list"),
    re_path(r'^rowers/(?P<pk>[0-9]+)/$', views.RowerDetail, name="rower-detail"),
    re_path(r'^races/$', RaceList.as_view(), name="race-list"),
    re_path(r'^races/(?P<pk>[0-9]+)/$', views.RaceDetail, name="race-detail"),
    re_path(r'^rankings/$', views.RankingView, name="ranking"),
    re_path(r'^competition/$', views.CompetitionView, name="comp-list"),
    re_path(r'^competition/(?P<pk>[0-9]+)/$', views.CompetitionResults, name="comp-detail"),
    re_path(r'^clubs/$', ClubList.as_view(), name="club-list"),
    re_path(r'^clubs/(?P<pk>[0-9]+)/$', views.ClubDetail, name="club-detail"),
    re_path(r'^edition/(?P<pk>[0-9]+)/$', views.EditionDetail, name="edition-detail"),
    re_path(r'^fixture/(?P<pk>[0-9]+)/$', views.FixtureDetail, name="fixture-detail"),
    #re_path(r'^compare/$', csrf_exempt(views.Compare), name="compare-index"),
    re_path(r'^compare/$', views.RowerCompare2, name="compare2"),
    re_path(r'^crewcompare/$', views.CrewCompare, name="crewcompare"),
    re_path(r'^rowing/hrr/(?P<pk>[0-9]+)/$', views.KnockoutView, name="knockouts"),
    re_path(r'^favicon\.ico$',RedirectView.as_view(url='/static/favicon.ico')),
    re_path(r'^weather/$', views.WeatherCalc, name="weather"),
    re_path(r'^rower/correct/(?P<pk>[0-9]+)/$', RowerCorrect, name="rower-correct"),
    re_path(r'^result/correct/(?P<pk>[0-9]+)/$', ResultCorrect, name="result-correct"),
    re_path(r'^rower/merge/(?P<pk>[0-9]+)/$',RowerMerge, name="rower-merge"),
    #re_path(r'^compare/(?P<pk1>[0-9]+)/(?P<pk2>[0-9]+)/$', views.RowerCompare, name="compare"),
    #re_path(r'^rower-autocomplete/$', RowerAutocomplete.as_view(), name="rower-autocomplete"),
    #re_path(r'rowerm2m/$', CrewUpdate.as_view(), name="crew-update"),

    # used in the search function on the rowers view
    re_path(r'^rowersearch/$', views.RowerSearch, name="rower-search"),
	
    # used in autoselect in admin
    re_path(r'^ajax_select/', include(ajax_select_urls)),
]

rowingstats/urls.py
from django.conf.urls import url, include, re_path
from django.contrib import admin

urlpatterns = [
    re_path(r'^admin/', admin.site.urls),
    re_path(r'^blog/', include('blog.urls')),
	re_path(r'^articles/', include('blog.urls')),
	re_path(r'^hrr/', include('hrr.urls')),
	re_path(r'^', include('rowing.urls')),
]

rowing/models.py
from django.db import models
from django.contrib.postgres.fields import JSONField

# commentary on the below
# TODO: Create ProgressionRule - ForeignKey of Race, which specifies how crews progress
# TODO: Possibly create CompetitionInstance - eg Rio Olympics

# HOCR, HRR, HORR, Marlow etc
class Competition(models.Model):
    name = models.CharField(max_length=200)
    
    def __str__(self):
        return self.name

# Event is M2-, W2x, Temple, PA etc, IM14+ - unique to each Competition (M2- of Olympics not M2- of World Cup)
class Event(models.Model):
    name = models.CharField(max_length=100)
    comp = models.ForeignKey(Competition, on_delete=models.PROTECT)
    
    type_choices = (
        ('Sweep', 'Sweep'),
        ('Sculling', 'Sculling'),
        ('Lwt Sweep', 'Lightweight Sweep'),
        ('Lwt Sculling', 'Lightweight Sculling'),
        ('Para-Sweep', 'Para-Sweep'),
        ('Para-Sculling', 'Para-Sculling'),
    )
    type = models.CharField(max_length=20, choices=type_choices, default='Sweep')
    
    boatsize_choices = (
        (1, 'Single'),
        (2, 'Pair/Double'),
        (4, 'Four/Quad'),
        (8, 'Eight/Octuple'),
        (0, 'Other'),
    )
    boatsize = models.IntegerField(choices=boatsize_choices, null=True, default=1)
    
    def __str__(self):
        return str(self.comp.name) +": "+ self.name
        
    def next(self):
        try:
            return Event.objects.get(pk=self.pk+1)
        except:
            return None
            
    def previous(self):
        try:
            return Event.objects.get(pk=self.pk-1)
        except:
            return None
    
    # old stackoverflow tip
    class Meta:
        ordering = ['comp__name', 'name']
    
class Rower(models.Model):
    name = models.CharField(max_length=100)
    
    # to be implemented, left out for now for simplicity
    #lightweight = models.BooleanField() - may be moved to be result attribute
    #u20 = lightweight = models.BooleanField()
    #u23 = lightweight = models.BooleanField()
    #BUCS = lightweight = models.BooleanField()
    #retired = boolean
    gender_choices = (
        ('M', 'M'),
        ('W', 'W'),
        ('U', 'U'),
    )
    gender = models.CharField(max_length=1, choices=gender_choices, default='M')
    nationality = models.CharField(max_length=8, default="GBR")
    #iscox = models.BooleanField(default=False)
    
    # world rowing ID number
    wrid = models.IntegerField(null=True, blank=True, verbose_name='World Rowing ID', unique=True)

    def __str__(self):
        return self.name
        
    last_updated = models.DateTimeField("Last updated", auto_now=True)
    created = models.DateTimeField("Created on", auto_now_add=True)

# Used to define a set of fixtures - e.g. the 2016 Olympics or 2017 HRR
class Edition(models.Model):
    name = models.CharField(max_length=100)
    comp = models.ForeignKey(Competition, on_delete=models.PROTECT)
    
    def __str__(self):
        return self.name

# Also known as Knockout in earlier version of this code (debating to rename this as a Tournament)
# This is the M2- at the Rio Olympics - it's a set of races within a given competition
class Fixture(models.Model):
    event = models.ForeignKey(Event, on_delete=models.PROTECT)
    edition = models.ForeignKey(Edition, on_delete=models.PROTECT)
    #rounds = models.PositiveSmallIntegerField(default=1)
    
    location = models.CharField(max_length=100, null=True, blank=True)
    
    def __str__(self):
        return (self.event.name + ' - ' + self.edition.name)

# M2- FA, Final of PA etc        
class Race(models.Model):
    name = models.CharField(max_length=200)
    date = models.DateField("Race date")
    starttime = models.TimeField("Race time", null=True, blank=True, help_text="When the race was scheduled to take place e.g. 13:00. NOT the racing results.")
    raceclass = models.CharField("Class", max_length=100, null=True, blank=True)
    event = models.ForeignKey(Event, on_delete=models.PROTECT)
    fixture = models.ForeignKey(Fixture, on_delete=models.PROTECT, null=True, blank=True, help_text="If this race is a part of a wider fixture (e.g. a specific regatta), specify it here. Optional - not needed for single race events e.g. the Boat Race")
    rnumber = models.IntegerField(null=True, blank=True, verbose_name="Race Number", help_text="If helpful, this can be used to store race numbers.")
    distance = models.IntegerField(default=2000, help_text="The race distance, in metres.")
    
    # for separating TTs, Heats, SFs and Fs conducted on the same day
    order_choices = (
        (0, 'TT/Heat/Single race'),
        (1, 'Semi-Final'),
        (2, 'Final'),
    )
    order = models.PositiveSmallIntegerField(default=0, choices=order_choices, help_text="Used to differentiate between races held on same day for rower scores. To be deprecated")
    round = models.IntegerField(null=True, blank=True, help_text="In a multi-round fixture, use this to differentiate between F, SF, Reps, QF, Heat 2, Heat 1, TTs etc")
    slot = models.IntegerField(null=True, blank=True, help_text="Within a round, this is the order of races, top to bottom on the tree. E.g. H1 will be round 1, slot 1; Heat 2 will be round 1, slot 2 etc; SFAB1 will be round 2, slot 1 etc.")
    
    complete = models.BooleanField(default=True, help_text="If set to True (checked) the Race will be used in calculating scores and displayed publicly. Leave unchecked for incomplete races. Useful for big races that need to be done in chunks.")
    last_updated = models.DateTimeField("Last updated", auto_now=True)
    created = models.DateTimeField("Created on", auto_now_add=True)
    
    # progression fields
    #progression = models.ManyToManyField('self', through='RaceLink', through_fields=('startrace','endrace'), symmetrical=False)
    
    # perhaps add predecessor and successor fields?

    def __str__(self):
        return self.name
        
    def next(self):
        try:
            return Race.objects.get(pk=self.pk+1)
        except:
            return None
            
    def previous(self):
        try:
            return Race.objects.get(pk=self.pk-1)
        except:
            return None

# used to create a map of races - eg linking semis to final
# creates a directed graph - e.g. positions 1,2,3 from heat to semi
# NB due to slightly funky history of this, access model via:
## from fixture: f.racelink_set.all()
## from race: r.next_races.all() or r.prior_races.all()
class RaceLink(models.Model):
    start = models.ForeignKey(Race, on_delete=models.CASCADE, related_name='next_races')
    end = models.ForeignKey(Race, on_delete=models.CASCADE, related_name='prior_races')
    fixture = models.ForeignKey(Fixture, on_delete=models.PROTECT)
    '''type_choices = (
        ('Predecessor', 'Predecessor'),
        ('Successor', 'Successor'),
    )
    type = models.CharField(max_length=15, choices=type_choices)'''
    
    positions = models.CharField(max_length=100, help_text="Specify which positions will progress as a comma-separated string e.g. 1,2,3")
    
    def __str__(self):
        return self.start.name + " progressing positions " + self.positions + " to " + self.end.name

class Club(models.Model):
    name = models.CharField(max_length=200)
    
    last_updated = models.DateTimeField("Last updated", auto_now=True)
    created = models.DateTimeField("Created on", auto_now_add=True)
    countrycode = models.CharField(max_length=3, help_text="Used for national crews, provides the nationality code in international races", blank=True, null=True)
    country = models.CharField(max_length=200, default="UK", null=True, blank=True)
    
    def __str__(self):
        return self.name
    
class Result(models.Model):
    race = models.ForeignKey(Race, on_delete=models.CASCADE)
    position = models.IntegerField(null=True, blank=True)
    crew = models.ManyToManyField(Rower, blank=True)
    # Not to store club membership for each rower, but indirectly through the race entry
    clubs = models.ManyToManyField(Club, blank=True)
    # eg A, B crew
    flag = models.CharField(max_length=10, null=True, blank=True)
    
    # to be implemented
    # club = foreignkey
    # time = timefields or perhaps 1toM relationship?
    # cox threw some errors and probably needs to be a M2M relationship too
    cox = models.ForeignKey(Rower, on_delete=models.SET_NULL, null=True, blank=True, related_name='cox')
    # lwt field - can be used for determining whether crew members are lightweight
    
    last_updated = models.DateTimeField("Last updated", auto_now=True)
    created = models.DateTimeField("Created on", auto_now_add=True)
    
    def __str__(self):
        return str(self.race)+": #"+str(self.position)
        
class Time(models.Model):
    result = models.ForeignKey(Result, on_delete=models.CASCADE)
    description = models.CharField(max_length=100)
    value = models.TimeField()
    order = models.PositiveSmallIntegerField(default=0)
    
    class Meta:
        unique_together = ['result', 'description']
        ordering = ['order']
        
    def __str__(self):
        return str(self.result.race.name) + ' (' + str(self.result.position) + ') - ' + self.description + ' :- ' + str(self.value) + ' (' + str(self.order) + ')'
        
class Alias(models.Model):
    rower = models.ForeignKey(Rower, on_delete=models.CASCADE)
    value = models.CharField(max_length=200)
    temp = models.BooleanField(default=False)
    
    # used to avoid filling with duplicates
    class Meta:
        unique_together = ['rower', 'value']
        verbose_name_plural = 'aliases'
        
    def __str__(self):
        return str(self.value) + " for " + str(self.rower.name)
        
class ClubAlias(models.Model):
    club = models.ForeignKey(Club, on_delete=models.CASCADE)
    value = models.CharField(max_length=200)
    
    # used to avoid filling with duplicates
    class Meta:
        unique_together = ['club', 'value']

rowing/templates/rowing/crew_compare.html
{% extends "rowing/base.html" %}
{% load static %}
{% block title %}Crew comparison{% endblock %}

{% block content %}
<div class="col-sm-12 row"><h2>Compare Crews{% if error != 3 %} - {{type}}{% endif %}</h2></div>

<form class="form-inline" action="/crewcompare/" method="get">

			<div class="form-group">{{form.crew1.label}}: {{form.crew1}}</div>
			<div class="form-group">{{form.crew2.label}}: {{form.crew2}}</div>

			<div class="form-group">{{form.type}}</div>
			<button class="btn btn-default" type="submit">Submit</button>

</form>
{% if error == 0 %}
<div class="col-sm-12 row"><p>&nbsp;</p></div>
<div class="col-sm-12 row"><p>Comparing the specified crews on their estimated {{type}} skill.</p></div>

<div class="col-sm-12 row"><h3>Current prediction</h3></div>
<div class="col-sm-12 row"><p>Based on the latest results we have in our database for each rower, we would currently expect 

{% if win_prob1 > win_prob2 %}
<strong>Crew 1</strong> would beat <strong>Crew 2</strong> in a one-on-one comparison <strong>{{win_prob1|floatformat:1}}%</strong>
{% else %}
<strong>Crew 2</strong> would beat <strong>Crew 1</strong> in a one-on-one comparison <strong>{{win_prob2|floatformat:1}}%</strong>
{% endif %}
 of the time.
</p>
<p>This prediction is based on the following data:</p>
</div>

<div class="container">
	<div class="row">
		
		<div class="col-md-6">
			<table class="table table-striped">
			<caption>Crew 1</caption>
			<thead><tr>
				<th>Name</th>
				<th>Skill</th>
				<th>Uncertainty</th>
				<th>Date of result</th>
			</tr></thead>
			<tbody>
				{% for r in rowers1 %}
				<tr>
					<td><a href="/rowers/{{r.0.pk}}">{{r.0.name}}</a></td>
					<td>{{r.1|floatformat:1}}</td>
					<td>{{r.2|floatformat:1}}</td>
					<td>{{r.3}}</td>
				</tr>
				{% endfor %}
				<tr>
					<td><strong>Total:</strong></td>
					<td>{{mu1|floatformat:1}}</td>
					<td>{{sigma1|floatformat:1}}</td>
					<td></td>
				</tr>
			</tbody>
			</table>
		</div>
		<div class="col-md-6">
			<table class="table table-striped">
			<caption>Crew 2</caption>
			<thead><tr>
				<th>Name</th>
				<th>Skill</th>
				<th>Uncertainty</th>
				<th>Date of result</th>
			</tr></thead>
			<tbody>
				{% for r in rowers2 %}
				<tr>
					<td><a href="/rowers/{{r.0.pk}}">{{r.0.name}}</a></td>
					<td>{{r.1|floatformat:1}}</td>
					<td>{{r.2|floatformat:1}}</td>
					<td>{{r.3}}</td>
				</tr>
				{% endfor %}
				<tr>
					<td><strong>Total:</strong></td>
					<td>{{mu2|floatformat:1}}</td>
					<td>{{sigma2|floatformat:1}}</td>
					<td></td>
				</tr>
			</tbody>
			</table>
		</div>
	</div>
</div>
{% endif %}

<div class="col-md-12"><p>&nbsp;</p></div>
{% endblock %}

{% block header_extra %}
<link rel="stylesheet" type="text/css" href="{% static 'rowing/css/highcharts.css' %}">
<script src="{% static 'rowing/js/highcharts.js' %}"></script>
{{form.media}}
{% endblock %}

rowing/templates/rowing/fixture_detail.html
{% extends "rowing/base.html" %}
{% block title %}{{fixture.edition.comp.name}} - {{fixture.edition.name}} - {{fixture.event.name}}{% endblock %}
{% block loadscript %}
<script>
// attempted workaround due to Django's baffling form habits
function selectElement(id, valueToSelect) {    
    let element = document.getElementById(id);
    element.value = valueToSelect;
}
function loadfunc(){
	selectElement('id_edition', {{init_edition|safe}});
	selectElement('id_event', {{init_event|safe}});
}
</script>
{% endblock %}
{% block header_extra %}<script>

// stupid script required to make it work and not get querystrings etc

function actionOnSubmit(id)
{
var e = document.getElementById(id);
location = "/fixture/" + e.options[e.selectedIndex].value;
return false;
}

</script>
<style>
	.table.vertical-align > tbody > tr > td {
		 vertical-align: middle;
	}
</style>
{% endblock %}
{% block content %}
<div class="col-sm-12 row"><h2>{{fixture.edition.comp.name}} - {{fixture.edition.name}} - {{fixture.event.name}}</h2><hr></div>

<div class="row">
<div class="col-sm-6"><h3>Switch edition</h3>
<form class="form-inline" action="/fixture" onSubmit="return actionOnSubmit('id_edition')" method="get" name="editionform">
        {% for field in editionform %}
        <div class="/*col-sm-2*/ form-group">{{field.options.count}}{{field}}</div>
        {% endfor %}
        <button class="btn btn-default" type="submit">Switch</button>
    
</form>
</div>
<div class="col-sm-6"><h3>Switch event</h3>
<form class="form-inline" action="/fixture" onSubmit="return actionOnSubmit('id_event')" method="get" name="eventform">
        {% for field in eventform %}
        <div class="/*col-sm-2*/ form-group">{{field.options.count}}{{field}}</div>
        {% endfor %}
        <button class="btn btn-default" type="submit">Switch</button>
    
</form>
</div>
</div>
<!--- TODO: add racelinks as arrows, convert to whizzy js thing --->

<div class="col-sm-12 row"><h3>Races in this event</h3></div>
<div class="col-sm-12 row">
{% if columns %}
<table class="vertical-align table">
	<tbody>
		<tr>
			{% for column in columns %}
			<td>
			<table class="table">
				
			{% for race in column %}
				<tr><td><a href="/races/{{race.pk}}/">{{race.name}}</a></td></tr>
			{% endfor %}
				
			</table>
			<td>
			{% endfor %}
		</tr>
	</tbody>
</table>
{% else %}
<p>No races are available for this event.</p>
{% endif %}
</div>

{% endblock %}

rowing/templates/rowing/index.html
{% extends "rowing/base.html" %}
{% block title %} Rowing Stats{% endblock %}
{% block content %}
	<div class="jumbotron">
	  <h1>Hello, world!</h1>
	  <p>This is a new website that aims to provide a complete database of all rowing results. It is freely available to all. It's a work in progress, so bear with us.</p>
	  <p><a class="btn btn-primary btn-lg" href="rankings" role="button">See the rankings</a></p>
	</div>

{% endblock %}

rowing/templates/rowing/knockoutdetail.html
{% extends "rowing/base.html" %}
{% block title %}{{knockout.event.name}} - {{knockout.year}}{% endblock %}

{% block content %}
<div class="col-sm-12 row"><h2>{{knockout.event.name}} - {{knockout.year}}</h2></div>

<div class="col-sm-12 row"><p>&nbsp;</p></div>
<div class="col-sm-12 row"><h3>Race tree</h3></div>
<div class="col-sm-12 row">
<table class="vertical-align table">
{% for krace in columns.0.1 %}
<tr>
	{% if krace.race %}
		{% if krace.bye == 1 %}
		<td>{{krace.race.name}}</td>
		{% else %}
		<td><a href="/races/{{krace.race.pk}}">{{krace.race.name}}</a></td>
		{% endif %}
	{% else %}
	<td>No associated race</td>
	{% endif %}
	
	{% if krace.slotz|divisibleby:'2' %}
	{% if krace.child %}
		{% if not krace.child.race %}
		<td rowspan="2">No associated race</td>
		{% elif krace.child.race.result_set.all|length > 0 %}
		<td rowspan="2"><a href="/races/{{krace.child.race.pk}}">{{krace.child.race.name}}</a></td>
		{% else %}
		<td rowspan="2">.....TBC.....</td>
		{% endif %}
	{% endif %}
	{% endif %}
	
	{% if krace.slotz|divisibleby:'4' %}
	{% if krace.child.child %}
		{% if not krace.child.child.race %}
		<td rowspan="4">No associated race</td>
		{% elif krace.child.child.race.result_set.all|length > 0 %}
		<td rowspan="4"><a href="/races/{{krace.child.child.race.pk}}">{{krace.child.child.race.name}}</a></td>
		{% else %}
		<td rowspan="4">.....TBC.....</td>
		{% endif %}
	{% endif %}
	{% endif %}
	
	{% if krace.slotz|divisibleby:'8' %}
	{% if krace.child.child.child %}
		{% if not krace.child.child.child.race %}
		<td rowspan="8">No associated race</td>
		{% elif krace.child.child.child.race.result_set.all|length > 0 %}
		<td rowspan="8"><a href="/races/{{krace.child.child.child.race.pk}}">{{krace.child.child.child.race.name}}</a></td>
		{% else %}
		<td rowspan="8">.....TBC.....</td>
		{% endif %}
	{% endif %}
	{% endif %}
	
	{% if krace.slotz|divisibleby:'16' %}
	{% if krace.child.child.child.child %}
		{% if not krace.child.child.child.child.race %}
		<td rowspan="16">No associated race</td>
		{% elif krace.child.child.child.child.race.result_set.all|length > 0 %}
		<td rowspan="16"><a href="/races/{{krace.child.child.child.child.race.pk}}">{{krace.child.child.child.child.race.name}}</a></td>
		{% else %}
		<td rowspan="16">.....TBC.....</td>
		{% endif %}
	{% endif %}
	{% endif %}
	
</tr>
{% endfor %}
</table>
</div>

<div class="col-sm-12 row"><h3>Win probabilities - <mark>Highly Experimental!</mark></h3></div>
<div class="col-sm-12 row">
<table class="table table-striped">
<caption>Predictions made for: <strong>{{rdayn}}</strong></caption>
	<thead>
		<tr>
			<th>Crew</th>
			<th>Probability of winning overall</th>
			{% if cumlprobs.1.odds %}
			<th>Odds on</th>
			{% endif %}
		</tr>
	</thead>
	<tbody>
		{% if cumlprobs %}
		{% for cumlprob in cumlprobs %}
		<tr>
			<td>{{cumlprob.crewname}}</td>
			<td>{{cumlprob.prob}}</td>
			{% if cumlprob.odds %}
			<td>{{cumlprob.odds}}</td>
			{% endif %}
		</tr>
		{% endfor %}
		{% else %}
		<tr><td colspan="5">No results to show</td></tr>
		{% endif %}
	</tbody>
</table>
</div>

<div class="col-md-12"><p>&nbsp;</p></div>
{% endblock %}

{% block header_extra %}
<link rel="stylesheet" type="text/css" href="{% static 'rowing/css/highcharts.css' %}">
<script src="{% static 'rowing/js/highcharts.js' %}"></script>
<style>
	.table.vertical-align > tbody > tr > td {
		 vertical-align: middle;
	}
</style>
{{form.media}}
{% endblock %}

rowing/templates/rowing/race_detail.html
{% extends "rowing/base.html" %}
{% block title %}{{object.name}} - Detail{% endblock %}
{% block header_extra %}
<style>
.vbottom {
    margin-top:20px;
}
</style>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script>
$(document).ready(function(){
  $("#correction").click(function(){
    $(".correct").toggleClass('hidden');
	});
});
</script>
{% endblock %}
{% block content %}
<div class="row"><div class="col-sm-10"><h2>{{object.name}}</h2></div>
</div>
<div class="col-sm-12 row"><p>Held on {{object.date}}</p></div>
{% if object.fixture %}
<div class="col-sm-12 row"><p>Part of <a href="/fixture/{{object.fixture.pk}}/">{{object.fixture}}</a> in <a href="/competition/{{object.event.comp.pk}}">{{object.event.comp.name}}</a></p></div>
{% else %}
<div class="col-sm-12 row"><p>Part of <a href="/competition/{{object.event.comp.pk}}/?event={{object.event.pk}}">{{object.event.name}}</a> in <a href="/competition/{{object.event.comp.pk}}">{{object.event.comp.name}}</a></p></div>
{% endif %}

<div class="row">
<div class="col-xs-6 col-sm-8 col-md-10"><h3>Results</h3></div>
<div class="col-xs-6 col-sm-4 col-md-2 vbottom"><button type="button" class="btn btn-info btn-sm" data-toggle="button" id="correction"><span class="glyphicon glyphicon-erase" aria-hidden="true"></span> Suggest correction</button></div>
</div>
<div class="row">
<div class="col-xs-12 table-responsive">
<table class="table table-striped">
	<thead>
		<tr>
			<th>Position</th>
			<th>Crew</th>
			<th>Club</th>
			{% if time_flag %}
			<th>Times</th>
			{% endif %}
		</tr>
	</thead>
	<tbody>
		{% if results %}
		{% for rank in results %}
		<tr>
			<td>{{rank.position}} <a href="{% url 'result-correct' pk=rank.pk %}"><button type="button" class="hidden correct btn btn-info btn-sm">Edit</button></a></td>
			<td>
				{% for member in rank.crew.all %}
					<a href="/rowers/{{member.pk}}">{{member.name}}</a>{% if not forloop.last %},{% else %}&nbsp;{% endif %}
				{% endfor %}
				{% if rank.cox %}
					<br /><strong>Cox: </strong><a href="/rowers/{{rank.cox.pk}}">{{rank.cox.name}}</a>
				{% endif %}
			</td>
			<td>
				{% if rank.clubs.all %}
					{% for member in rank.clubs.all %}
						<a href="/clubs/{{member.pk}}">{{member.name}}</a>{% if not forloop.last %},{% else %}&nbsp;{% endif %}
					{% endfor %}
				{% else %}
					<p>Club unknown</p>
				{% endif %}
				{% if rank.flag %}
				({{rank.flag}})
				{% endif %}
			</td>
			{% if rank.time_set.all %}
			<td>
				{% for t in rank.time_set.all %}
					<strong>{{t.description}}</strong>: {{t.value|time:"i:s"}}:{{t.value|time:"u"|slice:":2"}}{% if not forloop.last %},<br />{% else %}{% endif %}
				{% endfor %}
			</td>
			{% endif %}
			<!-- <td>{{rank.flag}}</td> -->
		</tr>
		{% endfor %}
		{% else %}
			<tr><td colspan="4"><p>No recorded scores</p></td></tr>
		{% endif %}
	</tbody>
</table>
</div>
</div>
{% endblock %}